
logging:
  level:
    root: INFO
    
spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: false
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
  
  security:
    oauth2:
      client:
        registration:
          oidcServices:
            authorization-grant-type: client_credentials
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
            - openid
        provider:
          oidcServices:
            token-uri: ${TOKEN_URI}
